### ISSUE TITLE
adding some authentication mechanism for the api

### ISSUE THREAD

**Issue by abramsymons** [BrightID/FS-Backup-Service#1]
Currently anyone can simply overwrite backup data that set by others.
We should add some authentication mechanism to the api to avoid this.

**Comment by abramsymons** [comment]
One approach is to use BrightID signing key for authentication. So users will use their (permanent) BrightID as their username and sign their request to the api with their signing key.
As signing key may be changed for BrightID users, the backup service should query the signing key of the BrightID every time it receive the request from the BrightID API and check if the user request signed by his/her latest signing key.
With this approach we are in fact relying on BrightID system and it's recovery mechanism for implementing an authentication module for an application.
The problem with this approach is that we may not want the applications have access to the BrightID of the users.

**Comment by abramsymons** [comment]
Another approach is to use hash of BrightID+password (that is used by user to encrypt data) as the key1 (instead of BrightID) when calling the api to store data ins. In this way, as no one knows the password, no one knows the key and can overwrite users data.
If we take this approach, there is no need to change anything on the backup service. Only mobile client should be changed to use the hash of BrightID+password as key1 when writing backup data and reading them.

**Comment by abramsymons** [comment]
If we take the first approach and use BrightID signing mechanism for authentication, we can solve the problem of DoS attack to the api by rate limiting based on BrightID too. Otherwise we should use fetchVerification and ids within context of application in future to solve the attack problem in future just like any other application use that.

**Comment by adamstallard** [comment]
> One approach is to use BrightID signing key for authentication. So users will use their (permanent) BrightID as their username and sign their request to the api with their signing key.
> As signing key may be changed for BrightID users, the backup service should query the signing key of the BrightID every time it receive the request from the BrightID API and check if the user request signed by his/her latest signing key.
> With this approach we are in fact relying on BrightID system and it's recovery mechanism for implementing an authentication module for an application.
> The problem with this approach is that we may not want the applications have access to the BrightID of the users.

I like this approach. Since we are in charge of this service, we know to not store the brightid. They are sending their brightid, but there is no plain text data associated with it, so it's fine. 

Uploading data requires a signed, timestamped request message. Also include a hash of the data being uploaded so a man-in-the-middle can't replace the backup payload. 

Downloading doesn't need a signature since the user may have lost their signing key.

**Comment by adamstallard** [comment]
> Another approach is to use hash of BrightID+password (that is used by user to encrypt data) as the key1 (instead of BrightID) when calling the api to store data ins. In this way, as no one knows the password, no one knows the key and can overwrite users data.
> If we take this approach, there is no need to change anything on the backup service. Only mobile client should be changed to use the hash of BrightID+password as key1 when writing backup data and reading them.

This is susceptible to a man-in-the-middle attack. If I snoop on your upload request, I can replace it with my own garbage data, destroying your backup.

**Comment by abramsymons** [comment]
> This is susceptible to a man-in-the-middle attack. If I snoop on your upload request, I can replace it with my own garbage data, destroying your backup.

As you mentioned we can simply solve this by using https.
So to keep things simple I take the second approach for now. So nothing will be changed here on this service and we only should update mobile clients using that.
Also we should deploy this service as an https service.
